/** Mentor recurring-availability rules.
 *
 *  GET  /api/availability
 *    List the current mentor's rules (active + inactive).
 *
 *  POST /api/availability
 *    Body: { dayOfWeek, startTime, endTime, recurMode, weeksAhead?, notes? }
 *    Create a rule and immediately materialize slots for the next 8 weeks.
 *    Returns the new rule plus a { created, updated, removed } cascade summary.
 *
 *  Slots themselves live in ScheduleSlot and are generated by
 *  src/lib/availability-cascade.ts — never written directly here.
 */

import { NextRequest, NextResponse } from "next/server";
import { supabase } from "@/lib/supabase";
import { getCurrentUser } from "@/lib/auth";
import { materializeAvailability, WEEKS_AHEAD } from "@/lib/availability-cascade";

const toMins = (t: string) => {
  const [h, m] = t.split(":").map(Number);
  return h * 60 + m;
};

const TIME_RE = /^([01]\d|2[0-3]):[0-5]\d$/;

/** Shared validation for create + update. Returns an error string or null. */
export function validateRule(body: {
  dayOfWeek?: unknown;
  startTime?: unknown;
  endTime?: unknown;
  recurMode?: unknown;
  weeksAhead?: unknown;
}): string | null {
  const { dayOfWeek, startTime, endTime, recurMode, weeksAhead } = body;

  if (typeof dayOfWeek !== "number" || !Number.isInteger(dayOfWeek) || dayOfWeek < 0 || dayOfWeek > 6) {
    return "dayOfWeek must be an integer 0 (Sunday) through 6 (Saturday).";
  }
  if (typeof startTime !== "string" || !TIME_RE.test(startTime)) return "startTime must be HH:MM.";
  if (typeof endTime !== "string" || !TIME_RE.test(endTime)) return "endTime must be HH:MM.";
  if (toMins(startTime) >= toMins(endTime)) return "startTime must be before endTime.";

  const dur = toMins(endTime) - toMins(startTime);
  if (dur < 60) return "A slot must be at least 60 minutes.";
  if (dur > 90) return "A slot must be at most 90 minutes.";

  if (recurMode !== "unlimited" && recurMode !== "fixed") {
    return 'recurMode must be "unlimited" or "fixed".';
  }
  if (recurMode === "fixed") {
    if (typeof weeksAhead !== "number" || !Number.isInteger(weeksAhead) || weeksAhead < 1 || weeksAhead > WEEKS_AHEAD) {
      return `weeksAhead must be an integer 1–${WEEKS_AHEAD} when recurMode is "fixed".`;
    }
  }
  return null;
}

export async function GET() {
  const user = await getCurrentUser();
  if (!user || user.role !== "mentor") return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const { data: rules, error } = await supabase
    .from("AvailabilityRule")
    .select("id, dayOfWeek, startTime, endTime, recurMode, weeksAhead, active, notes, createdAt, updatedAt")
    .eq("mentorId", user.userId)
    .order("dayOfWeek", { ascending: true })
    .order("startTime", { ascending: true });

  if (error) return NextResponse.json({ error: "Failed to fetch rules" }, { status: 500 });
  return NextResponse.json({ rules: rules || [] });
}

export async function POST(req: NextRequest) {
  const user = await getCurrentUser();
  if (!user || user.role !== "mentor") return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const body = await req.json();
  const issue = validateRule(body);
  if (issue) return NextResponse.json({ error: issue }, { status: 400 });

  const now = new Date().toISOString();
  const { data: rule, error } = await supabase
    .from("AvailabilityRule")
    .insert({
      id: crypto.randomUUID(),
      mentorId: user.userId,
      dayOfWeek: body.dayOfWeek,
      startTime: body.startTime,
      endTime: body.endTime,
      recurMode: body.recurMode,
      weeksAhead: body.recurMode === "fixed" ? body.weeksAhead : null,
      notes: body.notes ?? null,
      active: true,
      createdAt: now,
      updatedAt: now,
    })
    .select("id, dayOfWeek, startTime, endTime, recurMode, weeksAhead, active, notes")
    .single();

  if (error) return NextResponse.json({ error: "Failed to create rule" }, { status: 500 });

  const cascade = await materializeAvailability(user.userId);
  return NextResponse.json({ rule, cascade }, { status: 201 });
}
